from __future__ import annotations

import asyncio
import json
import os
import re
import sys
import time
from contextlib import AsyncExitStack
from datetime import UTC, datetime
from typing import Any

import ollama
from pydantic import BaseModel, Field

from agents import (
    ActionPayload,
    LocalizedPayload,
    RuntimeConstraints,
    ThinkingPayload,
    TrinityAgents,
    build_instruct_agent,
    build_instruct_finalize_input,
    build_instruct_handoff_input,
    build_jp_agent,
    build_jp_input,
    build_thinking_agent,
    build_thinking_input,
)
from mcp_runtime import MCPServerConfig, MCPToolRegistry, ToolExecutionRecord

EMPTY_MODEL_RESPONSE = "(No response generated by the model)"


class EngineConfig(BaseModel):
    ollama_host: str = Field(default_factory=lambda: os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434"))
    thinking_model: str = Field(default_factory=lambda: os.getenv("LFM_THINKING_MODEL", "lfm-thinking"))
    instruct_model: str = Field(default_factory=lambda: os.getenv("LFM_INSTRUCT_MODEL", "lfm-instruct"))
    jp_model: str = Field(default_factory=lambda: os.getenv("LFM_JP_MODEL", "lfm-jp"))
    target_locale: str = Field(default_factory=lambda: os.getenv("LFM_TARGET_LOCALE", "ja-JP"))
    max_tool_rounds: int = Field(default_factory=lambda: int(os.getenv("LFM_MAX_TOOL_ROUNDS", "4")), ge=1, le=8)
    request_timeout: float = Field(default_factory=lambda: float(os.getenv("LFM_REQUEST_TIMEOUT", "180")), gt=1)
    keep_alive: str | None = Field(default_factory=lambda: os.getenv("OLLAMA_KEEP_ALIVE", "10m"))
    allow_partial_mcp: bool = Field(default_factory=lambda: os.getenv("LFM_ALLOW_PARTIAL_MCP", "true").lower() != "false")
    constraints: RuntimeConstraints = Field(default_factory=RuntimeConstraints)
    mcp_servers: list[MCPServerConfig] = Field(default_factory=list)

    @classmethod
    def from_env(
        cls,
        *,
        mcp_servers: list[MCPServerConfig] | None = None,
    ) -> "EngineConfig":
        if mcp_servers is not None:
            return cls(mcp_servers=mcp_servers)

        raw_servers = os.getenv("MCP_SERVERS_JSON", "").strip()
        if not raw_servers:
            return cls()

        parsed = json.loads(raw_servers)
        servers = [MCPServerConfig.model_validate(item) for item in parsed]
        return cls(mcp_servers=servers)


class ModelTrace(BaseModel):
    agent: str
    model: str
    duration_ms: int
    prompt_tokens: int | None = None
    completion_tokens: int | None = None
    stop_reason: str | None = None
    raw_content: str | None = None
    raw_thinking: str | None = None


class OrchestrationResult(BaseModel):
    request: str
    locale: str
    reasoning: ThinkingPayload
    action: ActionPayload
    localized: LocalizedPayload
    stream: str
    tools: list[ToolExecutionRecord] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    traces: list[ModelTrace] = Field(default_factory=list)
    started_at: datetime
    completed_at: datetime

    @property
    def final_response(self) -> str:
        return self.localized.content


class OrchestratorError(RuntimeError):
    pass


class ModelInvocationError(OrchestratorError):
    pass


class OllamaGateway:
    def __init__(self, config: EngineConfig) -> None:
        self._config = config
        self._client = ollama.AsyncClient(host=config.ollama_host, timeout=config.request_timeout)

    async def chat(
        self,
        *,
        agent_name: str,
        model: str,
        messages: list[dict[str, Any]],
        tools: list[dict[str, Any]] | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[Any, ModelTrace]:
        started = time.perf_counter()
        try:
            response = await self._client.chat(
                model=model,
                messages=messages,
                tools=tools,
                options=options,
                keep_alive=self._config.keep_alive,
            )
        except Exception as exc:
            raise ModelInvocationError(f"{agent_name} model call failed: {exc}") from exc

        return response, self._build_trace(agent_name=agent_name, model=model, response=response, started=started)

    async def generate(
        self,
        *,
        agent_name: str,
        model: str,
        prompt: str,
        system: str | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[Any, ModelTrace]:
        started = time.perf_counter()
        try:
            response = await self._client.generate(
                model=model,
                prompt=prompt,
                system=system,
                options=options,
                keep_alive=self._config.keep_alive,
            )
        except Exception as exc:
            raise ModelInvocationError(f"{agent_name} model call failed: {exc}") from exc

        return response, self._build_trace(agent_name=agent_name, model=model, response=response, started=started)

    @staticmethod
    def _build_trace(*, agent_name: str, model: str, response: Any, started: float) -> ModelTrace:
        return ModelTrace(
            agent=agent_name,
            model=model,
            duration_ms=int((time.perf_counter() - started) * 1000),
            prompt_tokens=getattr(response, "prompt_eval_count", None),
            completion_tokens=getattr(response, "eval_count", None),
            stop_reason=getattr(response, "done_reason", None),
            raw_content=_extract_response_content(response),
            raw_thinking=_extract_response_thinking(response),
        )


class TrinityOrchestrator:
    def __init__(
        self,
        config: EngineConfig,
        *,
        agents: TrinityAgents | None = None,
        tool_registry: MCPToolRegistry | None = None,
    ) -> None:
        self.config = config
        self.agents = agents or TrinityAgents(
            thinking=build_thinking_agent(config.thinking_model),
            instruct=build_instruct_agent(config.instruct_model),
            jp=build_jp_agent(config.jp_model),
        )
        self.gateway = OllamaGateway(config)
        self.tool_registry = tool_registry or MCPToolRegistry(
            config.mcp_servers,
            allow_partial=config.allow_partial_mcp,
        )
        self._stack = AsyncExitStack()

    async def __aenter__(self) -> "TrinityOrchestrator":
        await self._stack.__aenter__()
        await self._stack.enter_async_context(self.tool_registry)
        return self

    async def __aexit__(self, exc_type: type[BaseException] | None, exc: BaseException | None, tb: Any) -> None:
        await self._stack.__aexit__(exc_type, exc, tb)

    async def run(self, user_prompt: str, *, context: dict[str, Any] | None = None) -> OrchestrationResult:
        started_at = datetime.now(UTC)
        warnings = list(self.tool_registry.startup_warnings)
        traces: list[ModelTrace] = []
        stream_blocks: list[str] = []

        reasoning, trace = await self._stage_thinking(
            user_prompt=user_prompt,
            context=context,
            stream_blocks=stream_blocks,
        )
        traces.append(trace)

        action, action_traces, tool_records, action_warnings = await self._stage_instruct(
            user_prompt=user_prompt,
            reasoning_content=reasoning.content,
            stream_blocks=stream_blocks,
        )
        traces.extend(action_traces)
        warnings.extend(action_warnings)

        localized, trace = await self._stage_jp(
            user_prompt=user_prompt,
            action_content=action.content,
            stream_blocks=stream_blocks,
        )
        traces.append(trace)

        return OrchestrationResult(
            request=user_prompt,
            locale=self.config.target_locale,
            reasoning=reasoning,
            action=action,
            localized=localized,
            stream=_join_stream(stream_blocks),
            tools=tool_records,
            warnings=warnings,
            traces=traces,
            started_at=started_at,
            completed_at=datetime.now(UTC),
        )

    async def _stage_thinking(
        self,
        *,
        user_prompt: str,
        context: dict[str, Any] | None,
        stream_blocks: list[str],
    ) -> tuple[ThinkingPayload, ModelTrace]:
        tool_catalog = self.tool_registry.render_catalog()
        prompt = _build_thinking_prompt(
            system_prompt=self.agents.thinking.system_prompt,
            user_input=build_thinking_input(
                user_prompt=user_prompt,
                locale=self.config.target_locale,
                constraints=self.config.constraints,
                tool_catalog=tool_catalog,
                context=context,
            ),
        )
        response, trace = await self.gateway.generate(
            agent_name=self.agents.thinking.name,
            model=self.agents.thinking.model,
            prompt=prompt,
            options=self.agents.thinking.options,
        )
        raw_reasoning = (_extract_response_content(response) or "").strip()
        trace.raw_content = raw_reasoning
        _log_agent_output("thinking", raw_reasoning)
        reasoning = ThinkingPayload(content=_coerce_stage_content(raw_reasoning))
        stream_blocks.append(reasoning.content)
        _log_stream("thinking", stream_blocks)
        return reasoning, trace

    async def _stage_instruct(
        self,
        *,
        user_prompt: str,
        reasoning_content: str,
        stream_blocks: list[str],
    ) -> tuple[ActionPayload, list[ModelTrace], list[ToolExecutionRecord], list[str]]:
        messages = self._build_instruct_handoff_messages(
            user_prompt=user_prompt,
            reasoning_content=reasoning_content,
        )
        draft_response, traces, tool_records, warnings = await self._run_instruct_tool_loop(
            messages=messages,
            stream_blocks=stream_blocks,
        )
        action, trace = await self._finalize_instruct_response(
            user_prompt=user_prompt,
            reasoning_content=reasoning_content,
            draft_response=draft_response,
            tool_records=tool_records,
        )
        stream_blocks.append(action.content)
        _log_stream("instruct", stream_blocks)
        traces.append(trace)
        return action, traces, tool_records, warnings

    def _build_instruct_handoff_messages(
        self,
        *,
        user_prompt: str,
        reasoning_content: str,
    ) -> list[dict[str, Any]]:
        return [
            {"role": "system", "content": self.agents.instruct.system_prompt},
            {
                "role": "user",
                "content": build_instruct_handoff_input(
                    user_prompt=user_prompt,
                    reasoning_content=reasoning_content,
                    tool_catalog=self.tool_registry.render_catalog(),
                ),
            },
        ]

    async def _run_instruct_tool_loop(
        self,
        *,
        messages: list[dict[str, Any]],
        stream_blocks: list[str],
    ) -> tuple[str, list[ModelTrace], list[ToolExecutionRecord], list[str]]:
        traces: list[ModelTrace] = []
        warnings: list[str] = []
        tool_records: list[ToolExecutionRecord] = []
        draft_response = ""
        tools = self.tool_registry.ollama_tools()

        for _ in range(self.config.max_tool_rounds):
            response, trace = await self.gateway.chat(
                agent_name=self.agents.instruct.name,
                model=self.agents.instruct.model,
                messages=messages,
                tools=tools or None,
                options=self.agents.instruct.options,
            )
            traces.append(trace)
            assistant_message = response.message.model_dump(exclude_none=True)
            messages.append(assistant_message)
            draft_response = (response.message.content or "").strip()
            _log_agent_output("instruct", draft_response)

            tool_calls = list(getattr(response.message, "tool_calls", None) or [])
            if not tool_calls:
                break

            tool_records.extend(
                await self._execute_instruct_tool_calls(
                    tool_calls=tool_calls,
                    messages=messages,
                    stream_blocks=stream_blocks,
                )
            )
        else:
            warnings.append("The instruct agent reached the maximum number of tool rounds.")

        return draft_response, traces, tool_records, warnings

    async def _execute_instruct_tool_calls(
        self,
        *,
        tool_calls: list[Any],
        messages: list[dict[str, Any]],
        stream_blocks: list[str],
    ) -> list[ToolExecutionRecord]:
        tool_records: list[ToolExecutionRecord] = []

        for tool_call in tool_calls:
            tool_name = tool_call.function.name
            tool_args = dict(tool_call.function.arguments)
            tool_result = await self.tool_registry.call_tool(tool_name, tool_args)
            tool_records.append(tool_result)
            stream_blocks.append(_render_tool_block(tool_result))
            _log_stream(f"instruct-tool:{tool_name}", stream_blocks)
            messages.append(tool_result.as_ollama_message())

        return tool_records

    async def _finalize_instruct_response(
        self,
        *,
        user_prompt: str,
        reasoning_content: str,
        draft_response: str,
        tool_records: list[ToolExecutionRecord],
    ) -> tuple[ActionPayload, ModelTrace]:
        response, trace = await self.gateway.chat(
            agent_name=f"{self.agents.instruct.name}-finalize",
            model=self.agents.instruct.model,
            messages=[
                {"role": "system", "content": self.agents.instruct.system_prompt},
                {
                    "role": "user",
                    "content": build_instruct_finalize_input(
                        user_prompt=user_prompt,
                        reasoning_content=reasoning_content,
                        draft_response=draft_response,
                        tool_results="\n\n".join(_render_tool_block(record) for record in tool_records),
                    ),
                },
            ],
            options=self.agents.instruct.options,
        )
        raw_action = (response.message.content or "").strip()
        trace.raw_content = raw_action
        _log_agent_output("instruct-finalize", raw_action)
        clean_action = _sanitize_content(raw_action)
        clean_draft = _sanitize_content(draft_response)
        action_content = clean_action or clean_draft or EMPTY_MODEL_RESPONSE
        return ActionPayload(content=action_content), trace

    async def _stage_jp(
        self,
        *,
        user_prompt: str,
        action_content: str,
        stream_blocks: list[str],
    ) -> tuple[LocalizedPayload, ModelTrace]:
        response, trace = await self.gateway.chat(
            agent_name=self.agents.jp.name,
            model=self.agents.jp.model,
            messages=[
                {"role": "system", "content": self.agents.jp.system_prompt},
                {
                    "role": "user",
                    "content": build_jp_input(
                        user_prompt=user_prompt,
                        locale=self.config.target_locale,
                        action_content=action_content,
                    ),
                },
            ],
            options=self.agents.jp.options,
        )
        raw_response = (response.message.content or "").strip()
        trace.raw_content = raw_response
        _log_agent_output("jp", raw_response)
        localized = LocalizedPayload(content=_coerce_stage_content(raw_response))
        stream_blocks.append(localized.content)
        _log_stream("jp", stream_blocks)
        return localized, trace


def _coerce_stage_content(raw_content: str) -> str:
    text = _sanitize_content(raw_content)
    return text or EMPTY_MODEL_RESPONSE


def _build_thinking_prompt(*, system_prompt: str, user_input: str) -> str:
    return f"{system_prompt.strip()}\n\n{user_input.strip()}".strip()


def _extract_response_content(response: Any) -> str | None:
    message = getattr(response, "message", None)
    if message is not None:
        return getattr(message, "content", None)
    return getattr(response, "response", None)


def _extract_response_thinking(response: Any) -> str | None:
    message = getattr(response, "message", None)
    if message is not None and getattr(message, "thinking", None) is not None:
        return getattr(message, "thinking", None)
    return getattr(response, "thinking", None)


def _strip_code_fences(raw_content: str) -> str:
    text = raw_content.strip()
    text = re.sub(r"```(?:[a-zA-Z0-9_-]+)?", "", text)
    return text.replace("```", "").strip()


def _sanitize_content(raw_content: str) -> str:
    text = _strip_code_fences(raw_content)
    text = re.sub(r"<\|[^>]+?\|>", "", text, flags=re.IGNORECASE)
    text = re.sub(r"</?think>", "", text, flags=re.IGNORECASE)
    text = re.sub(r"</?[a-zA-Z0-9_:-]+(?:\s[^>]*)?>", "", text)
    lines = [line.strip() for line in text.splitlines()]
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _log_agent_output(agent: str, raw_content: str) -> None:
    print(f"\n=== RAW {agent.upper()} OUTPUT ===", file=sys.stderr)
    print(raw_content or EMPTY_MODEL_RESPONSE, file=sys.stderr)
    print(f"=== END RAW {agent.upper()} OUTPUT ===", file=sys.stderr)


def _log_stream(stage: str, stream_blocks: list[str]) -> None:
    print(f"\n=== BATON AFTER {stage.upper()} ===", file=sys.stderr)
    print(_join_stream(stream_blocks) or "(empty baton)", file=sys.stderr)
    print(f"=== END BATON AFTER {stage.upper()} ===", file=sys.stderr)

def _join_stream(blocks: list[str]) -> str:
    return "\n---\n".join(block for block in blocks if block).strip()


def _render_tool_block(record: ToolExecutionRecord) -> str:
    payload = record.content.strip() or "(empty)"
    status = "error" if record.is_error else "ok"
    return (
        f"[tool alias={record.alias} server={record.server} status={status}]\n"
        f"{payload}\n"
        f"[end tool]"
    )


async def run_orchestrator(
    prompt: str,
    *,
    config: EngineConfig | None = None,
    context: dict[str, Any] | None = None,
) -> OrchestrationResult:
    engine = TrinityOrchestrator(config or EngineConfig.from_env())
    async with engine:
        return await engine.run(prompt, context=context)


def run(prompt: str, *, config: EngineConfig | None = None, context: dict[str, Any] | None = None) -> OrchestrationResult:
    return asyncio.run(run_orchestrator(prompt, config=config, context=context))
